@extends('layouts.app')
@section('title', 'Custom reports')
@section('content')
<div class="space-y-5">
  <div class="flex flex-wrap items-center gap-3"><div><h1 class="text-2xl font-bold">Custom reports</h1><p class="text-sm text-slate-400">Choose a date meaning, filters, grouping and columns. The CSV uses these same settings.</p></div><div class="flex-1"></div><a href="{{ route('reports.index') }}" class="rounded bg-slate-800 hover:bg-slate-700 px-3 py-2 text-sm">Quick Reports</a><a href="{{ route('reports.handover') }}" class="rounded bg-slate-800 hover:bg-slate-700 px-3 py-2 text-sm">Shift handover</a></div>
  @if ($errors->any()) <div class="rounded border border-red-700 bg-red-950/60 p-3 text-sm">@foreach ($errors->all() as $error)<div>{{ $error }}</div>@endforeach</div> @endif
  <form method="get" action="{{ route('reports.custom') }}" class="rounded-xl border border-slate-700 bg-slate-800/70 p-4 space-y-4">
    <div class="grid gap-3 md:grid-cols-3 lg:grid-cols-4 text-sm">
      <label><span class="block mb-1">From (Perth date)</span><input type="date" name="from" value="{{ $filters['from'] ?? '' }}" class="w-full rounded bg-slate-900 border border-slate-700 px-3 py-2"></label>
      <label><span class="block mb-1">To (Perth date)</span><input type="date" name="to" value="{{ $filters['to'] ?? '' }}" class="w-full rounded bg-slate-900 border border-slate-700 px-3 py-2"></label>
      <label><span class="block mb-1">Date means</span><select name="date_basis" class="w-full rounded bg-slate-900 border border-slate-700 px-3 py-2"><option value="opened" @selected($filters['date_basis'] === 'opened')>Actually started</option><option value="planned" @selected($filters['date_basis'] === 'planned')>Planned start</option><option value="active" @selected($filters['date_basis'] === 'active')>Active during date range</option></select></label>
      <label><span class="block mb-1">Status</span><select name="status" class="w-full rounded bg-slate-900 border border-slate-700 px-3 py-2"><option value="">All</option>@foreach (['pending','open','closed','cancelled'] as $status)<option value="{{ $status }}" @selected(($filters['status'] ?? '') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></label>
      <label><span class="block mb-1">Work type</span><select name="work_type_id" class="w-full rounded bg-slate-900 border border-slate-700 px-3 py-2"><option value="">All types</option>@foreach ($workTypes as $type)<option value="{{ $type->id }}" @selected(($filters['work_type_id'] ?? '') == $type->id)>{{ $type->name }}</option>@endforeach</select></label>
      <label><span class="block mb-1">Area at logging</span><select name="area_id" class="w-full rounded bg-slate-900 border border-slate-700 px-3 py-2"><option value="">All areas</option>@foreach ($areas as $area)<option value="{{ $area->id }}" @selected(($filters['area_id'] ?? '') == $area->id)>{{ $area->name }}</option>@endforeach</select></label>
      <label><span class="block mb-1">Saved location</span><select name="location_id" class="w-full rounded bg-slate-900 border border-slate-700 px-3 py-2"><option value="">All saved locations</option>@foreach ($locations as $location)<option value="{{ $location->id }}" @selected(($filters['location_id'] ?? '') == $location->id)>{{ $location->name }}{{ $location->status === 'archived' ? ' (archived)' : '' }}</option>@endforeach</select></label>
      <label><span class="block mb-1">Location name contains</span><input name="location_text" value="{{ $filters['location_text'] ?? '' }}" maxlength="120" placeholder="Also finds ad hoc locations" class="w-full rounded bg-slate-900 border border-slate-700 px-3 py-2"></label>
      <label><span class="block mb-1">ID, permit, notes, Other or reporter</span><input name="q" value="{{ $filters['q'] ?? '' }}" maxlength="120" class="w-full rounded bg-slate-900 border border-slate-700 px-3 py-2"></label>
      <label><span class="block mb-1">Summarise by</span><select name="group_by" class="w-full rounded bg-slate-900 border border-slate-700 px-3 py-2">@foreach (['none'=>'No grouping','type'=>'Work type','other_type'=>'Other descriptions','location'=>'Location name','area'=>'Area','status'=>'Status','day'=>'Date'] as $key => $label)<option value="{{ $key }}" @selected($filters['group_by'] === $key)>{{ $label }}</option>@endforeach</select></label>
    </div>
    <fieldset><legend class="text-sm font-semibold mb-2">Columns to display and export</legend><div class="flex flex-wrap gap-3 text-sm">@foreach ($columns as $key => $label)<label class="flex items-center gap-1 rounded bg-slate-900 px-2 py-1"><input type="checkbox" name="columns[]" value="{{ $key }}" @checked(in_array($key, $filters['columns'], true))> {{ $label }}</label>@endforeach</div></fieldset>
    <div class="flex flex-wrap items-center gap-2"><button class="rounded bg-emerald-600 hover:bg-emerald-500 px-4 py-2 font-semibold">Run report</button><a href="{{ route('reports.custom.csv', request()->query()) }}" class="rounded bg-slate-700 hover:bg-slate-600 px-4 py-2">Download this CSV</a><a href="{{ route('reports.custom') }}" class="text-sm text-slate-300 underline px-2">Clear</a></div>
    <p class="text-xs text-slate-400">Saved location matches by original catalogue ID; Location name contains searches the name captured on the job. If both are set, both must match. Planned excludes unscheduled jobs; Active excludes pending/cancelled jobs. Dates use Australia/Perth.</p>
  </form>
  <div class="rounded border border-slate-700 bg-slate-800/70 px-4 py-3 font-semibold">{{ number_format($total) }} matching job(s)</div>
  @if ($grouped)
    <section class="rounded border border-slate-700 bg-slate-800/70 p-4"><h2 class="font-semibold mb-2">Summary</h2><div class="overflow-x-auto"><table class="w-full text-sm"><thead><tr class="text-left"><th class="p-2">Group</th><th class="p-2 text-right">Jobs</th></tr></thead><tbody>@foreach ($grouped as $label => $count)<tr class="border-t border-slate-700"><td class="p-2">{{ $label }}</td><td class="p-2 text-right">{{ number_format($count) }}</td></tr>@endforeach</tbody></table></div></section>
  @endif
  <div class="overflow-x-auto rounded border border-slate-700"><table class="w-full min-w-[900px] text-sm"><thead class="bg-slate-950 text-left"><tr>@foreach ($filters['columns'] as $column)<th class="p-3 whitespace-nowrap">{{ $columns[$column] }}</th>@endforeach</tr></thead><tbody class="divide-y divide-slate-800">@forelse ($rows as $row)<tr>@foreach ($filters['columns'] as $column)<td class="p-3 align-top">{{ $row[$column] ?? '—' }}</td>@endforeach</tr>@empty<tr><td colspan="{{ count($filters['columns']) }}" class="p-8 text-center text-slate-400">No matching jobs.</td></tr>@endforelse</tbody></table></div>
  {{ $rows->links() }}
</div>
@endsection
