@extends('layouts.app')
@section('title', 'Shift handover')
@push('head')<style>@media print { nav, footer, .handover-controls { display:none!important } body { background:white!important;color:black!important } .handover-sheet { max-width:none!important } table { width:100%;font-size:10px } tr { break-inside:avoid } }</style>@endpush
@section('content')
<div class="max-w-7xl mx-auto space-y-5 handover-sheet">
  <div class="flex flex-wrap items-center gap-3"><div><h1 class="text-2xl font-bold">Shift handover</h1><p class="text-sm text-slate-400">Generated {{ now()->format('d M Y H:i') }} Australia/Perth · selected window {{ $start->format('d M Y H:i') }}–{{ $end->format('d M Y H:i') }}</p></div><div class="flex-1"></div><a href="{{ route('reports.index') }}" class="handover-controls rounded bg-slate-800 px-3 py-2 text-sm">Reports</a><button type="button" onclick="window.print()" class="handover-controls rounded bg-emerald-700 px-3 py-2 text-sm">Print / save PDF</button></div>
  <form method="get" class="handover-controls flex flex-wrap items-end gap-3 rounded bg-slate-800 p-4 text-sm"><label>From (Perth)<input name="from" type="datetime-local" value="{{ $start->format('Y-m-d\TH:i') }}" required class="block rounded bg-slate-900 border border-slate-700 px-3 py-2"></label><label>To (Perth)<input name="to" type="datetime-local" value="{{ $end->format('Y-m-d\TH:i') }}" required class="block rounded bg-slate-900 border border-slate-700 px-3 py-2"></label><button class="rounded bg-slate-700 px-4 py-2">Update window</button></form>
  <p class="text-xs text-slate-400">Open at end is reconstructed from stored start/close times; cancelled pending jobs are excluded. Activity includes jobs started or closed/cancelled in the window. Pending lists planned jobs for the 12 hours after the selected end. Check the live board for the current operational state.</p>
  @foreach ([['Open at handover', $stillOpen], ['Changed during shift', $activity], ['Pending next 12 hours', $upcoming]] as [$title, $entries])
  <section class="rounded border border-slate-700 p-4"><h2 class="text-lg font-semibold mb-2">{{ $title }} ({{ $entries->count() }})</h2><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-sm"><thead class="text-left bg-slate-900"><tr><th class="p-2">HRW ID</th><th class="p-2">Status</th><th class="p-2">Work type</th><th class="p-2">Location / area</th><th class="p-2">Start / planned</th><th class="p-2">Close</th><th class="p-2">Permit</th><th class="p-2">Notes / reporter</th></tr></thead><tbody>@forelse ($entries as $entry)<tr class="border-t border-slate-700 align-top"><td class="p-2 font-mono">{{ $entry->hrw_ref }}</td><td class="p-2">{{ ucfirst($entry->status) }}</td><td class="p-2">{{ $entry->workType?->is_other ? 'Other — '.$entry->other_description : ($entry->workType?->name ?? '—') }}</td><td class="p-2">{{ $entry->location_label }}<span class="block text-xs">{{ $entry->area?->name ?? '—' }}</span></td><td class="p-2">{{ ($entry->status === 'pending' ? $entry->planned_start_at : $entry->opened_at)?->format('d M H:i') }}</td><td class="p-2">{{ $entry->closed_at?->format('d M H:i') ?? '—' }}</td><td class="p-2">{{ $entry->permit_no ?: '—' }}</td><td class="p-2">{{ $entry->notes ?: '—' }}<span class="block text-xs">{{ $entry->reported_by ?: '—' }}</span></td></tr>@empty<tr><td colspan="8" class="p-4 text-center">None</td></tr>@endforelse</tbody></table></div></section>
  @endforeach
</div>
@endsection
